
server.port: 8110
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: http://localhost:8080/realms/master
          jwk-set-uri: http://localhost:8080/realms/nwo-realm/protocol/openid-connect/certs